import { useTheme } from 'next-themes';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { ReactNode, useId, useState } from 'react';
import Select, { StylesConfig } from 'react-select';

interface Option {
  value: string;
  label: string;
}
const options = [
  { value: 'EN', label: 'EN' },
  { value: 'BN', label: 'BN' },
  { value: 'AR', label: 'AR' },
];
const langOptions = [
  { value: 'English', label: 'English' },
  { value: 'Spanish', label: 'Spanish' }
]
const decimalOptions = [
  { value: 'Decimal', label: 'Decimal' },
  { value: 'Odds', label: 'Odds' }
]
type Props = {
  children: ReactNode;
  // Other props
}
export default function Layout({ children }: Props) {
  const { theme, setTheme } = useTheme();
  const [selectedOption, setSelectedOption] = useState<Option | null | unknown>(options[0]);
  const [selectedLangOption, setSelectedLangOption] = useState<Option | null | unknown>(langOptions[0]);
  const [selectedDacimalOption, setSelectedDacimalOption] = useState<Option | null | unknown>(decimalOptions[0]);
  const [openMenu, setOpenMenu] = useState(false)
  const [openMenu2, setOpenMenu2] = useState(false)
  const inactiveTheme = theme === "light" ? "dark" : "light";
  const {pathname} = useRouter()
  
  const customStyles: StylesConfig = {
    control: (provided, state) => ({
      ...provided,
      backgroundColor: theme !== "dark" ? "#1F493F" : "#D5DDEC",
      borderColor: '#1F493F',
      border: state.isFocused ? '0' : '0',
    }),
    option: (provided,state) => ({
      ...provided,
      color: state.isSelected?'#ffffff':'#000',
      backgroundColor: state.isSelected?'#1F493F':'#ffffff'
    }),
    singleValue: base => ({
      ...base,
      color: theme !== "dark" ? "#fff" : "#000",
      border: 'none'
    }),
  };

  return (
    <>
      <Head>
        <title>Online Bets -  Sports Betting Website HTML Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="header-section header-hidden">
          <div className="header-wrapper">
            <div className="menu-logo-adjust d-flex align-items-center">
              <div className="logo-menu me-5">
                <Link href="/" className="logo">
                  <img src="/img/logo/logo.png" alt="logo" />
                </Link>
                <Link href="/" className="dark-logo">
                  <img src="/img/logo/dark-logo.png" alt="logo" />
                </Link>
              </div>
              <div className={`header-bar ${openMenu && 'active act'}`} onClick={() => setOpenMenu(!openMenu)}>
                <span></span>
                <span></span>
                <span></span>
              </div>
              <ul className={`main-menu ${openMenu && 'active act'}`}>
                <li className="active">
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/live">Live</Link>
                </li>
                <li>
                  <Link href="/football">Sports</Link>
                </li>
                <li>
                  <Link href="/cricket">V-Sport</Link>
                </li>
                <li>
                  <Link href="/profile">Promotions</Link>
                </li>
                <li>
                  <Link href="/cricket">eSports</Link>
                </li>
                <li>
                  <Link href="#0" data-bs-toggle="modal" data-bs-target="#exampleModal2">Quick Bets</Link>
                </li>
                <li className="menu--btn">
                  <Link href="#0" className="btn--two" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    <span>Log In</span>
                  </Link>
                </li>
                <li className="menu--btn">
                  <Link href="#0" className="cmn--btn" data-bs-toggle="modal" data-bs-target="#exampleModal2">
                    <span>Sign Up</span>
                  </Link>
                </li>
              </ul>
            </div>
            <div className="right-menu-reature">
              <div className="language">
                <div className='d-flex gap-2 align-items-center'>
                  {/* <span className="current">En</span>
                  <ul className="list">
                    <li data-value="1" className="option selected focus">En</li>
                    <li data-value="2" className="option">Bn</li>
                    <li data-value="3" className="option">Us</li>
                  </ul> */}

                  <div className="glo">
                    <i className="fas fa-globe"></i>
                  </div>
                  <Select
                    instanceId={useId()}
                    defaultValue={selectedOption}
                    onChange={setSelectedOption}
                    options={options}
                    components={{
                      IndicatorSeparator: () => null,
                    }}
                    styles={customStyles}
                  />
                </div>
              </div>
              <div className="mode--toggle" onClick={() => setTheme(inactiveTheme)}>
                <img src={`/img/${theme === 'dark' ? 'moon' : 'sun'}.png`} alt="" />
              </div>
              <div className="signup-area">
                <Link href="#0" className="btn--two" data-bs-toggle="modal" data-bs-target="#exampleModal">
                  <span>
                    Log In
                  </span>
                </Link>
                <Link href="#0" className="cmn--btn" data-bs-toggle="modal" data-bs-target="#exampleModal2">
                  <span>
                    Sign Up
                  </span>
                </Link>
              </div>
            </div>
          </div>
        </header>
        {/* <!--==== Header top End  ====== --> */}

        {/* <!--Main Body Section Here--> */}
        {/* <!--Main Body Section Here--> */}
        <div className="main-body">
          {/* <!--Left Box Menu--> */}
          <div className="left-site-menu">
            <div className="left-box">
              <header className="header">
                <nav className={`menu ${openMenu2 && 'active act'}`}>
                  <ul className="main-list-menu">
                    <li>
                      <ul className="menu-promot menu-promot-first">
                        <li>
                          <form action="#">
                            <input type="text" placeholder="Search........." />
                            <span className="icon">
                              <i className="fas fa-magnifying-glass"></i>
                            </span>
                          </form>
                        </li>
                        <li>
                          <Link href="/" className={`${pathname == '/' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-home"></i>
                            </div>
                            <span>
                              Home
                            </span>
                          </Link>
                          <Link href="live" className={`main-list-menu-live ${pathname == '/live' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-live"></i>
                            </div>
                            <span>
                              Live
                            </span>
                            <span className="live-watch">
                              10
                            </span>
                          </Link>
                          <Link href="favorites"  className={`${pathname == '/favorites' && 'active'}`}>
                            <div className="icon">
                              <i className="fas fa-star"></i>
                            </div>
                            <span>
                              Fovarites
                            </span>
                          </Link>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <ul className="menu-promot menu-promot-bottom">
                        <li className="pro">
                          Games
                        </li>
                        <li className="original-sub">
                          <div className="dd">
                            <div className={`dd-a d-flex align-items-center justify-content-between`}>
                              <div className={`cont d-flex align-items-center`}>
                                <div className="icon">
                                  <i className="icon-football"></i>
                                </div>
                                <span>
                                  Football
                                </span>
                              </div>
                              <span>
                                <i className="fas fa-angle-down"></i>
                              </span>
                            </div>
                            <input type="checkbox" />
                            <div className="dd-c">
                              <ul>
                                <li>
                                  <Link href="football">
                                    <div className="icon">
                                      <i className="icon-football"></i>
                                    </div>
                                    <span>
                                      Football
                                    </span>
                                  </Link>
                                </li>
                                <li>
                                  <Link href="efootball">
                                    <div className="icon">
                                      <i className="icon-football"></i>
                                    </div>
                                    <span>
                                      eFootball
                                    </span>
                                  </Link>
                                </li>
                                <li>
                                  <Link href="football">
                                    <div className="icon">
                                      <i className="icon-football"></i>
                                    </div>
                                    <span>
                                      bFootball
                                    </span>
                                  </Link>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </li>
                        <li>
                          <Link href="efootball"  className={`${pathname == '/efootball' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-football"></i>
                            </div>
                            <span>
                              eFootball
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="csgo"  className={`${pathname == '/csgo' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-scgo"></i>
                            </div>
                            <span>
                              CS:GO
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="basketball"  className={`${pathname == '/basketball' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-basketball"></i>
                            </div>
                            <span>
                              Basketball
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="ebasketball"  className={`${pathname == '/ebasketball' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-basketball"></i>
                            </div>
                            <span>
                              eBasketball
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="tennis"  className={`${pathname == '/tennis' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-tennis"></i>
                            </div>
                            <span>
                              Tennis
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="etennis"  className={`${pathname == '/etennis' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-etennis"></i>
                            </div>
                            <span>
                              eTennis
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="dota2"  className={`${pathname == '/dota2' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-dota"></i>
                            </div>
                            <span>
                              Dota 2
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="lol"  className={`${pathname == '/lol' && 'active'}`}>
                            <div className="icon">
                              <i className="fas fa-star"></i>
                            </div>
                            <span>
                              LOL
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="icehocky"  className={`${pathname == '/icehocky' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-hockyball"></i>
                            </div>
                            <span>
                              Ice hockey
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="ehocky" className={`${pathname == '/ehocky' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-hockyman"></i>
                            </div>
                            <span>
                              eHockey
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="table-tennis" className={`${pathname == '/table-tennis' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-tabletennis"></i>
                            </div>
                            <span>
                              Table Tennis
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="volleyball" className={`${pathname == '/volleyball' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-volleyball"></i>
                            </div>
                            <span>
                              Volleyball
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="baseball"  className={`${pathname == '/baseball' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-baseball"></i>
                            </div>
                            <span>
                              Baseball
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="rugby" className={`${pathname == '/rugby' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-rugby"></i>
                            </div>
                            <span>
                              Rugby
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="mma"  className={`${pathname == '/mma' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-mma"></i>
                            </div>
                            <span>
                              MMA
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="americanfootball"  className={`${pathname == '/americanfootball' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-americanball"></i>
                            </div>
                            <span>
                              American Football
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="handball"  className={`${pathname == '/handball' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-handball"></i>
                            </div>
                            <span>
                              Handball
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="rocket"  className={`${pathname == '/rocket' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-rocketluage"></i>
                            </div>
                            <span>
                              Rocket League
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="boxing"  className={`${pathname == '/boxing' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-boxing"></i>
                            </div>
                            <span>
                              Boxing
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="rainbow"  className={`${pathname == '/rainbow' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-rainbow"></i>
                            </div>
                            <span>
                              Rainbow 6
                            </span>
                          </Link>
                        </li>                       
                        <li>
                          <Link href="futsal"  className={`${pathname == '/futsal' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-futsal"></i>
                            </div>
                            <span>
                              Futsal
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="cricket"  className={`${pathname == '/cricket' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-cricket"></i>
                            </div>
                            <span>
                              Cricket
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="sc2"  className={`${pathname == '/sc2' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-sc2"></i>
                            </div>
                            <span>
                              SC 2
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="ow"  className={`${pathname == '/ow' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-ow"></i>
                            </div>
                            <span>
                              OW
                            </span>
                          </Link>
                        </li>
                        <li>
                          <Link href="valor"  className={`${pathname == '/valor' && 'active'}`}>
                            <div className="icon">
                              <i className="icon-valor"></i>
                            </div>
                            <span>
                              Arena of Valor
                            </span>
                          </Link>
                        </li>
                      </ul>
                    </li>
                  </ul>
                  <div className={`hamburger ${openMenu2 && 'active act'}`} onClick={() => setOpenMenu2(!openMenu2)}>
                    <span></span>
                  </div>
                  <div className={`hamb ${openMenu2 && 'active act'}`} onClick={() => setOpenMenu2(!openMenu2)}>
                    <span></span>
                  </div>
                  <div className={`dimmer ${openMenu2 && 'active act'}`}></div>
                </nav>
              </header>
            </div>
          </div>
          {/* <!--Left Box Menu--> */}

          {/* <!--Middle Body--> */}
          <div className="body-middle">


            {children}
            {/* // <!--Footer Section--> */}
            <footer className="footer-section">
              <div className="container">
                <div className="footer-wrapper">
                  <p>
                    Copyright {new Date().getFullYear().toString()} <Link href="#0" className="text-base">OnlineBets</Link> All Rights Reserved.
                  </p>
                  <ul className="footer-link">
                    <li>
                      <Link href="#0">
                        Affiliate program
                      </Link>
                    </li>
                    <li>
                      <Link href="#0">
                        Terms & conditions
                      </Link>
                    </li>
                    <li>
                      <Link href="#0">
                        Bonus terms & conditions
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </footer>
            {/* // <!--Footer Section--> */}
            <Link href="#0" className="click-btn" data-bs-toggle="modal" data-bs-target="#exampleModal3">
              <i className="icon-basketball"></i>
            </Link>
          </div>
          {/* // <!--Middle Body--> */}




          {/* // <!--Right Box Chat--> */}
          <div className="right-site-menu">
            <div className="right-box">
              <div className="right-wrapper-area">
                <div className="blance-items">
                  <div className="left-blance">
                    <span><img src="/img/header/right-icon/wallet.svg" alt="icon" /></span>
                    <span className="text-blabce">Balance</span>
                  </div>
                  <span className="blance">
                    $300
                  </span>
                </div>
                <div className="betslip-wrapper">
                  <Link href="#0" className="left-betslip">
                    <span className="bed2"><img src="/img/header/right-icon/bed2.png" alt="icon" /></span>
                    <span className="bed1"><img src="/img/header/right-icon/bed.svg" alt="icon" /></span>
                    <span className="text-bets">Bet Slip</span>
                  </Link>
                  <Link href="#0" className="left-betslip">
                    <span><img src="/img/header/right-icon/bets.svg" alt="icon" /></span>
                    <span className="text-bets">My Bets</span>
                  </Link>
                </div>
                <div className="combo-box">
                  <ul className="nav">
                    <li className="nav-item">
                      <Link className="nav-link link-secondary" id="combo-tab" data-bs-toggle="tab" data-bs-target="#coombo" href="#"><span>Single bets</span></Link>
                    </li>
                    <li className="nav-item">
                      <Link className="nav-link link-secondary active" id="bets-tab" data-bs-toggle="tab" data-bs-target="#bbets" href="#"><span>Combo</span></Link>
                    </li>
                  </ul>
                  <div className="tab-content" id="tabContentboxes">
                    <div className="tab-pane fade" id="coombo" role="tabpanel" >
                      <div className="combo-wrapper">
                        <div className="combo-wrapper">
                          <div className="close-box">
                            <div className="close-items">
                              <div className="close-head">
                                <span>Latvia vs Moldova</span>
                                <span className="close">
                                  <i className="fas fa-xmark"></i>
                                </span>
                              </div>
                              <div className="match-fixing">
                                <div className="match-items">
                                  <div className="match-items-left">
                                    <div className="icon">
                                      <img src="/img/header/right-icon/footaball.svg" alt="icon" />
                                    </div>
                                    <div className="cont">
                                      <span>Moldova</span>
                                      <span className="winner">Match Winner</span>
                                    </div>
                                  </div>
                                  <div className="match-items-right">
                                    <div className="icon">
                                      <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                    </div>
                                    <span>5.20</span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="combo-switch">
                            <span>
                              Accept all odds changes
                            </span>
                            <label className="switch-com">
                              <input type="checkbox" className="checkbox" hidden />
                              <span className="checkbox-label">
                                <span className="ball"></span>
                              </span>
                            </label>
                          </div>
                          <div className="ammount-items">
                            <form action="#">
                              <input type="number" placeholder="Bet Amount" />
                              <button type="submit">
                                Max
                              </button>
                            </form>
                          </div>
                          <div className="possible-win">
                            <span>Possible win</span>
                            <span className="amount">$300</span>
                          </div>
                          <div className="combo-footer">
                            <Link href="#0" className="cmn--btn">
                              <span> Place Bet $300</span>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="tab-pane fade show active" id="bbets" role="tabpanel">
                      <div className="combo-wrapper">
                        <div className="close-box">
                          <div className="close-items">
                            <div className="close-head">
                              <span>Scotland vs Ukraine</span>
                              <span className="close">
                                <i className="fas fa-xmark"></i>
                              </span>
                            </div>
                            <div className="match-fixing">
                              <div className="match-items">
                                <div className="match-items-left">
                                  <div className="icon">
                                    <img src="/img/header/right-icon/footaball.svg" alt="icon" />
                                  </div>
                                  <div className="cont">
                                    <span>Scotland</span>
                                    <span className="winner">Match Winner</span>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                  </div>
                                  <span>3.20</span>
                                </div>
                              </div>
                              <div className="match-items">
                                <div className="match-items-left">
                                  <div className="icon">
                                    <img src="/img/header/right-icon/footaball.svg" alt="icon" />
                                  </div>
                                  <div className="cont">
                                    <span>Draw</span>
                                    <span className="winner">Match Winner</span>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                  </div>
                                  <span>4.60</span>
                                </div>
                              </div>
                              <p>
                                Add 2 more outcome(s) with odds greater than 1.4 to get x1.08
                              </p>
                              <div className="match-items match-progress">
                                <div className="match-items-left">
                                  <div className="prabox-wrap">
                                    <div className="terminal-bar">
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                    </div>
                                    <div className="bar-count">
                                      <p>x1.08</p>
                                      <p>x1,15</p>
                                      <p>x1.20</p>
                                      <p>x1.50</p>
                                    </div>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                  </div>
                                  <span>1.00</span>
                                </div>
                              </div>
                              <div className="match-items match-odds">
                                <div className="match-items-left">
                                  <div className="cont">
                                    <span>Total odds</span>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                  </div>
                                  <span>12.19</span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="combo-switch">
                          <span>
                            Accept all odds changes
                          </span>
                          <label className="switch-com">
                            <input type="checkbox" className="checkbox" hidden />
                            <span className="checkbox-label">
                              <span className="ball"></span>
                            </span>
                          </label>
                        </div>
                        <div className="ammount-items">
                          <form action="#">
                            <input type="number" placeholder="Bet Amount" />
                            <button type="submit">
                              Max
                            </button>
                          </form>
                        </div>
                        <div className="possible-win">
                          <span>Possible win</span>
                          <span className="amount">$300</span>
                        </div>
                        <div className="combo-footer">
                          <Link href="#0" className="cmn--btn">
                            <span> Place Bet $300</span>
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="accordion-box">
                  <div className="accordion" id="accordionExample">
                    <div className="accordion-item">
                      <div className="accordion-header" id="headingThree">
                        <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                          <span className="icon"><i className="fa-sharp fa-solid fa-gear"></i></span>
                          <span>Settings</span>
                        </button>
                        <div id="collapseThree" className="accordion-collapse collapse" data-bs-parent="#accordionExample">
                          <div className="accordion-body">
                            <div className="select-wrap">
                              <div className="select-one">
                                <Select
                                  instanceId={useId()}
                                  defaultValue={selectedLangOption}
                                  onChange={setSelectedLangOption}
                                  options={langOptions}
                                  components={{
                                    IndicatorSeparator: () => null,
                                  }}
                                  styles={customStyles}
                                />

                              </div>
                              <div className="select-two">
                                <Select
                                  instanceId={useId()}
                                  defaultValue={selectedDacimalOption}
                                  onChange={setSelectedDacimalOption}
                                  options={decimalOptions}
                                  components={{
                                    IndicatorSeparator: () => null,
                                  }}
                                  styles={customStyles}
                                />

                              </div>
                            </div>
                            <Link href="#0" className="condition-box">
                              Terms & Conditions
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="popular-bets">
                <div className="head">
                  <h6>
                    Popular bets
                  </h6>
                </div>
                <ul className="popoular-body">
                  <li className="popular-items">
                    <label className="popular-itmes-left">
                      <input className="form-check-input" type="checkbox" id="flexCheckDefault1" />
                      <span className="icon">
                        <i className="icon-football"></i>
                      </span>
                      <span className="cont">
                        <span className="text1">
                          1x2
                        </span>
                        <span className="text2">
                          Prance
                        </span>
                        <span className="text3">
                          France - Austria
                        </span>
                      </span>
                    </label>
                    <div className="popular-itmes-right">
                      <span>
                        2.37
                      </span>
                    </div>
                  </li>
                  <li className="popular-items">
                    <label className="popular-itmes-left">
                      <input className="form-check-input" type="checkbox" id="flexCheckDefault2" />
                      <span className="icon">
                        <i className="icon-football"></i>
                      </span>
                      <span className="cont">
                        <span className="text1">
                          1x2
                        </span>
                        <span className="text2">
                          Turkey
                        </span>
                        <span className="text3">
                          Turkey - Luxembourg
                        </span>
                      </span>
                    </label>
                    <div className="popular-itmes-right">
                      <span>
                        1.37
                      </span>
                    </div>
                  </li>
                  <li className="popular-items">
                    <label className="popular-itmes-left">
                      <input className="form-check-input" type="checkbox" id="flexCheckDefault3" />
                      <span className="icon">
                        <i className="icon-football"></i>
                      </span>
                      <span className="cont">
                        <span className="text1">
                          1x2
                        </span>
                        <span className="text2">
                          Alkmaar
                        </span>
                        <span className="text3">
                          Alkmaar - Apollon
                        </span>
                      </span>
                    </label>
                    <div className="popular-itmes-right">
                      <span>
                        3.47
                      </span>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          {/* // <!--Right Box Chat--> */}
        </div>
        {/* // <!--Main Body Section End--> */}
        {/* // <!--Main Body Section End--> */}

        {/* // <!-- Popup Section Start --> */}
        <div className="modal mylogin signup-popup fade" id="exampleModal" tabIndex={-1} aria-hidden="true">
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="modal-header">
                <div className="head">
                  <h5>
                    Sign into your account
                  </h5>
                  <p>
                    Don't have an account? <Link href="#0" className="text-base">Sign up</Link>
                  </p>
                </div>
              </div>
              <button type="button" className="btn-close cross-btn" data-bs-dismiss="modal" aria-label="Close"></button>
              <div className="modal-body">
                <div className="register-from">
                  <form action="#0">
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="email3" className="form-label">Email</label>
                        <input type="email" id="email3" placeholder="Your Email" />
                      </div>
                    </div>
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="password-field" className="form-label">Password</label>
                        <div className="form-group">
                          <input id="password-field" type="password" className="form-control" placeholder="Your Password" name="password" />
                          <span id="#password-field" className="fa fa-fw fa-eye field-icon toggle-password"></span>
                        </div>
                      </div>
                    </div>
                    <div className="items">
                      <div className="remember d-flex align-items-center justify-content-between">
                        <div className="form-check">
                          <label className="form-check-label" htmlFor="flexCheckDefault22">
                            <input className="form-check-input" type="checkbox" id="flexCheckDefault22" />
                            Remember me
                          </label>
                        </div>
                        <Link href="#0" className="forget">
                          Forget password?
                        </Link>
                      </div>
                    </div>
                    <div className="items text-center">
                      <button type="submit" className="cmn--btn cd-popup-close repopup">
                        <span>Start Playing</span>
                      </button>
                    </div>
                    <div className="orbar">
                      <span>OR</span>
                    </div>
                    <ul className="log-social">
                      <li>
                        <Link href="#0">
                          <i className="fab fa-steam-symbol"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-twitter"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-linkedin-in"></i>
                        </Link>
                      </li>
                    </ul>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="modal mylogin fade" id="exampleModal2" tabIndex={-1} aria-hidden="true">
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="modal-header">
                <div className="head">
                  <h5>
                    Create New Account
                  </h5>
                  <p>
                    Already have an account? <Link href="#0" className="text-base">Login</Link>
                  </p>
                </div>
              </div>
              <button type="button" className="btn-close cross-btn" data-bs-dismiss="modal" aria-label="Close"></button>
              <div className="modal-body">
                <div className="register-from">
                  <form action="#0">
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="uname" className="form-label">Username</label>
                        <input type="text" id="uname" placeholder="Your Username" />
                      </div>
                    </div>
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="email33" className="form-label">Email</label>
                        <input type="email" id="email33" placeholder="Your Email" />
                      </div>
                    </div>
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="password-field" className="form-label">Password</label>
                        <div className="form-group">
                          <input id="password-field2" type="password" className="form-control" placeholder="Your Password" name="password" />
                          <span id="#password-field2" className="fa fa-fw fa-eye field-icon toggle-password2"></span>
                        </div>
                      </div>
                    </div>
                    <div className="items">
                      <div className="check-area">
                        <div className="form-check">
                          <input className="form-check-input" type="checkbox" id="ones1" />
                          <label className="form-check-label" htmlFor="ones1">
                            I certify that I am at least 18 years of age
                          </label>
                        </div>
                        <div className="form-check">
                          <input className="form-check-input" type="checkbox" id="ones2" />
                          <label className="form-check-label" htmlFor="ones2">
                            I agree to the <Link href="#0" className="text-base">Privacy Policy</Link>
                          </label>
                        </div>
                        <div className="form-check">
                          <input className="form-check-input" type="checkbox" id="ones3" />
                          <label className="form-check-label" htmlFor="ones3">
                            I want to receive <Link href="#0" className="text-base">news and offers</Link>
                          </label>
                        </div>
                      </div>
                    </div>
                    <div className="items text-center">
                      <button type="submit" className="cmn--btn cd-popup-close repopup">
                        <span>Start Playing</span>
                      </button>
                    </div>
                    <div className="orbar">
                      <span>OR</span>
                    </div>
                    <ul className="log-social">
                      <li>
                        <Link href="#0">
                          <i className="fab fa-steam-symbol"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-twitter"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-linkedin-in"></i>
                        </Link>
                      </li>
                    </ul>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* // <!--menu modal--> */}
        <div className="modal right-menu-modal fade" id="exampleModal3" tabIndex={-1} aria-hidden="true">
          <div className="modal-dialog modal-sm">
            <div className="modal-content">
              <button type="button" className="btn-close cross-btn" data-bs-dismiss="modal" aria-label="Close"></button>
              <div className="modal-body">
                <div className="right-site-menu">
                  <div className="right-box">
                    <div className="right-wrapper-area">
                      <div className="blance-items">
                        <div className="left-blance">
                          <span><img src="/img/header/right-icon/wallet.svg" alt="icon" /></span>
                          <span className="text-blabce">Balance</span>
                        </div>
                        <span className="blance">
                          $300
                        </span>
                      </div>
                      <div className="betslip-wrapper">
                        <Link href="#0" className="left-betslip">
                          <span><img src="/img/header/right-icon/bed.svg" alt="icon" /></span>
                          <span className="text-bets">Bet Slip</span>
                        </Link>
                        <Link href="#0" className="left-betslip">
                          <span><img src="/img/header/right-icon/bets.svg" alt="icon" /></span>
                          <span className="text-bets">My Bets</span>
                        </Link>
                      </div>
                      <div className="combo-box">
                        <ul className="nav">
                          <li className="nav-item">
                            <Link className="nav-link link-secondary" data-bs-toggle="tab" data-bs-target="#coombomobile" href="#"><span>Single bets</span></Link>
                          </li>
                          <li className="nav-item">
                            <Link className="nav-link link-secondary active" data-bs-toggle="tab" data-bs-target="#bbetsmobile" href="#"><span>Combo</span></Link>
                          </li>
                        </ul>
                        <div className="tab-content" id="tabContentboxesmobile">
                          <div className="tab-pane fade" id="coombomobile" role="tabpanel" >
                            <div className="combo-wrapper">
                              <div className="combo-wrapper">
                                <div className="close-box">
                                  <div className="close-items">
                                    <div className="close-head">
                                      <span>Latvia vs Moldova</span>
                                      <span className="close">
                                        <i className="fas fa-xmark"></i>
                                      </span>
                                    </div>
                                    <div className="match-fixing">
                                      <div className="match-items">
                                        <div className="match-items-left">
                                          <div className="icon">
                                            <img src="/img/header/right-icon/footaball.svg" alt="icon" />
                                          </div>
                                          <div className="cont">
                                            <span>Moldova</span>
                                            <span className="winner">Match Winner</span>
                                          </div>
                                        </div>
                                        <div className="match-items-right">
                                          <div className="icon">
                                            <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                          </div>
                                          <span>5.20</span>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div className="combo-switch">
                                  <span>
                                    Accept all odds changes
                                  </span>
                                  <label className="switch-com">
                                    <input type="checkbox" className="checkbox" hidden />
                                    <span className="checkbox-label">
                                      <span className="ball"></span>
                                    </span>
                                  </label>
                                </div>
                                <div className="ammount-items">
                                  <form action="#">
                                    <input type="number" placeholder="Bet Amount" />
                                    <button type="submit">
                                      Max
                                    </button>
                                  </form>
                                </div>
                                <div className="possible-win">
                                  <span>Possible win</span>
                                  <span className="amount">$300</span>
                                </div>
                                <div className="combo-footer">
                                  <Link href="#0" className="cmn--btn">
                                    <span> Place Bet $300</span>
                                  </Link>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="tab-pane fade show active" id="bbetsmobile" role="tabpanel">
                            <div className="combo-wrapper">
                              <div className="close-box">
                                <div className="close-items">
                                  <div className="close-head">
                                    <span>Scotland vs Ukraine</span>
                                    <span className="close">
                                      <i className="fas fa-xmark"></i>
                                    </span>
                                  </div>
                                  <div className="match-fixing">
                                    <div className="match-items">
                                      <div className="match-items-left">
                                        <div className="icon">
                                          <img src="/img/header/right-icon/footaball.svg" alt="icon" />
                                        </div>
                                        <div className="cont">
                                          <span>Scotland</span>
                                          <span className="winner">Match Winner</span>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                        </div>
                                        <span>3.20</span>
                                      </div>
                                    </div>
                                    <div className="match-items">
                                      <div className="match-items-left">
                                        <div className="icon">
                                          <img src="/img/header/right-icon/footaball.svg" alt="icon" />
                                        </div>
                                        <div className="cont">
                                          <span>Draw</span>
                                          <span className="winner">Match Winner</span>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                        </div>
                                        <span>4.60</span>
                                      </div>
                                    </div>
                                    <p>
                                      Add 2 more outcome(s) with odds greater than 1.4 to get x1.08
                                    </p>
                                    <div className="match-items match-progress">
                                      <div className="match-items-left">
                                        <div className="prabox-wrap">
                                          <div className="terminal-bar">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                          </div>
                                          <div className="bar-count">
                                            <p>x1.08</p>
                                            <p>x1,15</p>
                                            <p>x1.20</p>
                                            <p>x1.50</p>
                                          </div>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                        </div>
                                        <span>1.00</span>
                                      </div>
                                    </div>
                                    <div className="match-items match-odds">
                                      <div className="match-items-left">
                                        <div className="cont">
                                          <span>Total odds</span>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img src="/img/header/right-icon/uptodwon.svg" alt="icon" />
                                        </div>
                                        <span>12.19</span>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className="combo-switch">
                                <span>
                                  Accept all odds changes
                                </span>
                                <label className="switch-com">
                                  <input type="checkbox" className="checkbox" hidden />
                                  <span className="checkbox-label">
                                    <span className="ball"></span>
                                  </span>
                                </label>
                              </div>
                              <div className="ammount-items">
                                <form action="#">
                                  <input type="number" placeholder="Bet Amount" />
                                  <button type="submit">
                                    Max
                                  </button>
                                </form>
                              </div>
                              <div className="possible-win">
                                <span>Possible win</span>
                                <span className="amount">$300</span>
                              </div>
                              <div className="combo-footer">
                                <Link href="#0" className="cmn--btn">
                                  <span> Place Bet $300</span>
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="accordion-box">
                        <div className="accordion" id="accordionExamplemy">
                          <div className="accordion-item">
                            <div className="accordion-header" id="headingThree03">
                              <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                <span className="icon"><i className="fa-sharp fa-solid fa-gear"></i></span>
                                <span>Settings</span>
                              </button>
                              <div id="collapseThreethree" className="accordion-collapse collapse" data-bs-parent="#accordionExample">
                                <div className="accordion-body">
                                  <Link href="#0" className="condition-box">
                                    Terms & Conditions
                                  </Link>
                                  <div className="select-wrap">
                                    <div className="select-one">
                                      <Select
                                        instanceId={useId()}
                                        defaultValue={selectedLangOption}
                                        onChange={setSelectedLangOption}
                                        options={langOptions}
                                        components={{
                                          IndicatorSeparator: () => null,
                                        }}
                                        styles={customStyles}
                                      />
                                    </div>
                                    <div className="select-two">
                                      <Select
                                        instanceId={useId()}
                                        defaultValue={selectedDacimalOption}
                                        onChange={setSelectedDacimalOption}
                                        options={decimalOptions}
                                        components={{
                                          IndicatorSeparator: () => null,
                                        }}
                                        styles={customStyles}
                                      />
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="popular-bets">
                      <div className="head">
                        <h6>
                          Popular bets
                        </h6>
                      </div>
                      <ul className="popoular-body">
                        <li className="popular-items">
                          <label className="popular-itmes-left">
                            <input className="form-check-input" type="checkbox" id="flexCheckDefault4" />
                            <span className="icon">
                              <i className="icon-football"></i>
                            </span>
                            <span className="cont">
                              <span className="text1">
                                1x2
                              </span>
                              <span className="text2">
                                Prance
                              </span>
                              <span className="text3">
                                France - Austria
                              </span>
                            </span>
                          </label>
                          <div className="popular-itmes-right">
                            <span>
                              2.37
                            </span>
                          </div>
                        </li>
                        <li className="popular-items">
                          <label className="popular-itmes-left">
                            <input className="form-check-input" type="checkbox" id="flexCheckDefault5" />
                            <span className="icon">
                              <i className="icon-football"></i>
                            </span>
                            <span className="cont">
                              <span className="text1">
                                1x2
                              </span>
                              <span className="text2">
                                Turkey
                              </span>
                              <span className="text3">
                                Turkey - Luxembourg
                              </span>
                            </span>
                          </label>
                          <div className="popular-itmes-right">
                            <span>
                              1.37
                            </span>
                          </div>
                        </li>
                        <li className="popular-items">
                          <label className="popular-itmes-left">
                            <input className="form-check-input" type="checkbox" id="flexCheckDefault6" />
                            <span className="icon">
                              <i className="icon-football"></i>
                            </span>
                            <span className="cont">
                              <span className="text1">
                                1x2
                              </span>
                              <span className="text2">
                                Alkmaar
                              </span>
                              <span className="text3">
                                Alkmaar - Apollon
                              </span>
                            </span>
                          </label>
                          <div className="popular-itmes-right">
                            <span>
                              3.47
                            </span>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}